version: "3.9"
services:
  tp-frontend:
    container_name: tp-frontend
    image: node:14-buster-slim
    volumes:
    - "../training-program-frontend:/usr/src/app"
    - "/usr/src/app/node_modules"
    working_dir: "/usr/src/app"
    command: ["npm", "run", "dev:smart"]
    ports: ["3000:3000"]

  # tp-backend:
  #   container_name: tp-backend
  #   image: node:14-buster-slim
  #   volumes:
  #   - "../training-program-backend:/usr/src/app"
  #   - "/usr/src/app/node_modules"
  #   working_dir: "/usr/src/app"
  #   command: ["npm", "run", "dev:smart"]
  #   ports: ["3001:3000"]
